/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get service health
         * @description Public endpoint returning basic service status, configured version, and current UTC time.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prometheus metrics
         * @description Public Prometheus text endpoint, registered only when `metrics.prometheus_enabled=true`.
         *
         *     The endpoint is rendered from the same latest-state snapshot consumed by the TUI. It includes price, funding,
         *     order book, market/instrument, arbitrage, related-signal, alert, and provider-health metric families.
         */
        get: operations["getPrometheusMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest tickers and funding rates */
        get: operations["getPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order-books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order book summaries or filtered full order books
         * @description Without query filters, returns compact `OrderBookSummary` records.
         *     When any supported filter is supplied, returns full matching `OrderBook`
         *     records.
         */
        get: operations["getOrderBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get configured providers */
        get: operations["getProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get provider health */
        get: operations["getProviderHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arbitrage/triangular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get triangular arbitrage estimates */
        get: operations["getTriangularArbitrage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arbitrage/cross-exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cross-exchange arbitrage estimates */
        get: operations["getCrossExchangeArbitrage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arbitrage/spot-futures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get spot-futures basis estimates */
        get: operations["getSpotFuturesArbitrage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ibkr/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get configured IBKR instruments
         * @description Returns IBKR instrument market info derived from configured instrument universes. Live data support is partial.
         */
        get: operations["getIBKRInstruments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ibkr/fx-triangular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get IBKR FX triangular estimates
         * @description Strategy endpoint returning results when configured IBKR FX market data is available.
         */
        get: operations["getIBKRFXTriangular"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ibkr/crypto-futures-basis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get crypto spot vs IBKR futures basis estimates
         * @description Strategy endpoint returning results when relevant crypto spot and IBKR futures data is available.
         */
        get: operations["getIBKRCryptoFuturesBasis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/related-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get related asset signals */
        get: operations["getRelatedAssetSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest alerts */
        get: operations["getAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchanges/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exchange health
         * @description Legacy health endpoint retained for compatibility. It currently overlaps with provider health.
         */
        get: operations["getExchangeHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get aggregate backend snapshot
         * @description Returns the complete latest-state snapshot consumed by the TUI.
         */
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example v2.1.0 */
            version: string;
            /** Format: date-time */
            time: string;
        };
        /**
         * @description Financial decimal value represented by `shopspring/decimal.Decimal` JSON serialization.
         * @example 67210.20
         */
        Decimal: string | number;
        /**
         * @description Decimal encoded as a string for precision-safe ingestion.
         * @example 67210.20
         */
        StringDecimal: string;
        /** @enum {string} */
        MarketType: "spot" | "futures";
        PricesResponse: {
            prices: {
                [key: string]: components["schemas"]["Ticker"][];
            };
            futures_prices: {
                [key: string]: components["schemas"]["Ticker"][];
            };
            funding_rates: components["schemas"]["FundingRate"][];
        };
        Ticker: {
            provider?: string;
            exchange: string;
            broker?: string;
            instrument_id?: string;
            display_name?: string;
            /** @example BTC/USDT */
            symbol: string;
            /** @example BTC */
            base_asset: string;
            /** @example USDT */
            quote_asset: string;
            market_type: components["schemas"]["MarketType"];
            /** @example crypto */
            asset_class: string;
            bid: components["schemas"]["Decimal"];
            ask: components["schemas"]["Decimal"];
            last: components["schemas"]["Decimal"];
            /** Format: date-time */
            updated_at: string;
        };
        FundingRate: {
            exchange: string;
            symbol: string;
            rate: components["schemas"]["Decimal"];
            /** Format: date-time */
            next_funding_time: string;
            /** Format: date-time */
            updated_at: string;
        };
        OrderBookLevel: {
            price: components["schemas"]["Decimal"];
            quantity: components["schemas"]["Decimal"];
        };
        OrderBook: {
            provider: string;
            exchange: string;
            broker?: string;
            symbol: string;
            instrument_id?: string;
            base_asset: string;
            quote_asset: string;
            market_type: components["schemas"]["MarketType"];
            asset_class: string;
            bids: components["schemas"]["OrderBookLevel"][];
            asks: components["schemas"]["OrderBookLevel"][];
            /** Format: date-time */
            updated_at: string;
            limited_depth?: boolean;
        };
        OrderBookSummary: {
            provider: string;
            exchange: string;
            broker?: string;
            symbol: string;
            market_type: components["schemas"]["MarketType"];
            best_bid: string;
            best_ask: string;
            /** Format: int32 */
            bid_levels: number;
            /** Format: int32 */
            ask_levels: number;
            age_seconds: string;
            /** Format: date-time */
            updated_at: string;
        };
        MarketInfo: {
            provider?: string;
            exchange: string;
            broker?: string;
            symbol: string;
            instrument_id?: string;
            display_name?: string;
            base_asset: string;
            quote_asset: string;
            asset_class: string;
            market_type: components["schemas"]["MarketType"];
            active: boolean;
        };
        ExchangeHealth: {
            provider?: string;
            /** @enum {string} */
            provider_type?: "crypto_exchange" | "broker";
            exchange: string;
            broker?: string;
            enabled: boolean;
            spot_enabled: boolean;
            /** @description For OKX, Bybit, Coinbase, Gate.io, and Bitget this is currently accepted in config but reported as partial because only spot public REST is implemented. */
            futures_enabled: boolean;
            market_data_enabled?: boolean;
            trading_enabled: boolean;
            websocket_enabled: boolean;
            websocket_connected: boolean;
            gateway_connected?: boolean;
            market_data_ok?: boolean;
            /** Format: date-time */
            last_message_time: string;
            /** Format: date-time */
            last_message_at: string;
            rest_fallback_active: boolean;
            /** Format: int32 */
            reconnect_count: number;
            last_error?: string;
            data_fresh: boolean;
            /** Format: int32 */
            stale_ticker_count: number;
            /** Format: int32 */
            stale_order_book_count: number;
            partial_support: boolean;
            /** Format: int32 */
            score: number;
            /** @enum {string} */
            status: "ok" | "degraded" | "stale" | "disconnected";
        };
        HealthMap: {
            [key: string]: components["schemas"]["ExchangeHealth"];
        };
        ProviderResponse: {
            /**
             * @description Provider identity. Supported crypto exchange values are `okx`, `bybit`, `binance`, `kraken`, `coinbase`, `gateio`, and `bitget`; broker support currently includes `ibkr`.
             * @example okx
             */
            name: string;
            /** @enum {string} */
            type: "crypto_exchange" | "broker";
            enabled: boolean;
            config: components["schemas"]["ProviderConfig"];
        };
        ProviderConfig: {
            enabled?: boolean;
            /** @enum {string} */
            type?: "crypto_exchange" | "broker";
            spot_enabled?: boolean;
            futures_enabled?: boolean;
            websocket_enabled?: boolean;
            /**
             * @description Go duration string.
             * @example 2s
             */
            rest_poll_interval?: string;
            market_data_enabled?: boolean;
            trading_enabled?: boolean;
            crypto_spot_enabled?: boolean;
            fx_enabled?: boolean;
            stocks_enabled?: boolean;
            etfs_enabled?: boolean;
            /** @example tws_gateway */
            api_mode?: string;
            /** @example 127.0.0.1 */
            host?: string;
            /**
             * Format: int32
             * @example 7497
             */
            port?: number;
            /**
             * Format: int32
             * @example 101
             */
            client_id?: number;
            fees?: components["schemas"]["ProviderFees"];
        };
        ProviderFees: {
            spot_taker?: components["schemas"]["Decimal"];
            futures_taker?: components["schemas"]["Decimal"];
            fx_estimated_taker?: components["schemas"]["Decimal"];
            futures_estimated_taker?: components["schemas"]["Decimal"];
        };
        LegSimulation: {
            from_asset: string;
            to_asset: string;
            symbol: string;
            /** @enum {string} */
            side: "buy" | "sell";
            input_amount: components["schemas"]["Decimal"];
            output_amount: components["schemas"]["Decimal"];
            average_price: components["schemas"]["Decimal"];
            fee_amount: components["schemas"]["Decimal"];
            slippage_percent: components["schemas"]["Decimal"];
            complete_fill: boolean;
        };
        TriangularOpportunityV2: {
            provider: string;
            exchange: string;
            strategy_title: string;
            asset_class?: string;
            cycle: string[];
            start_asset: string;
            start_amount: components["schemas"]["Decimal"];
            end_amount: components["schemas"]["Decimal"];
            net_profit_percent: components["schemas"]["Decimal"];
            complete_fill: boolean;
            worst_leg: string;
            max_slippage_percent: components["schemas"]["Decimal"];
            legs: components["schemas"]["LegSimulation"][];
            status: string;
            /** Format: date-time */
            updated_at: string;
        };
        CrossExchangeOpportunityV2: {
            strategy_title: string;
            symbol: string;
            buy_provider: string;
            sell_provider: string;
            buy_exchange: string;
            sell_exchange: string;
            trade_size: components["schemas"]["Decimal"];
            buy_average_price: components["schemas"]["Decimal"];
            sell_average_price: components["schemas"]["Decimal"];
            buy_slippage_percent: components["schemas"]["Decimal"];
            sell_slippage_percent: components["schemas"]["Decimal"];
            buy_fee_amount: components["schemas"]["Decimal"];
            sell_fee_amount: components["schemas"]["Decimal"];
            net_profit_percent: components["schemas"]["Decimal"];
            complete_fill: boolean;
            status: string;
            /** Format: date-time */
            updated_at: string;
        };
        SpotFuturesOpportunityV2: {
            strategy_title: string;
            provider: string;
            exchange: string;
            symbol: string;
            trade_size: components["schemas"]["Decimal"];
            spot_average_buy_price: components["schemas"]["Decimal"];
            futures_average_sell_price: components["schemas"]["Decimal"];
            spot_slippage_percent: components["schemas"]["Decimal"];
            futures_slippage_percent: components["schemas"]["Decimal"];
            spot_fee_amount: components["schemas"]["Decimal"];
            futures_fee_amount: components["schemas"]["Decimal"];
            basis_percent: components["schemas"]["Decimal"];
            funding_rate: components["schemas"]["Decimal"];
            net_estimate_percent: components["schemas"]["Decimal"];
            complete_fill: boolean;
            status: string;
            /** Format: date-time */
            updated_at: string;
        };
        BrokerFuturesBasisOpportunity: {
            strategy_title: string;
            asset: string;
            spot_provider: string;
            spot_symbol: string;
            spot_ask: components["schemas"]["Decimal"];
            futures_provider: string;
            futures_instrument_id: string;
            futures_display_name: string;
            futures_bid: components["schemas"]["Decimal"];
            basis_percent: components["schemas"]["Decimal"];
            net_estimate_percent: components["schemas"]["Decimal"];
            complete_fill: boolean;
            status: string;
            /** Format: date-time */
            updated_at: string;
        };
        RelatedAssetGroupSignal: {
            group: string;
            assets: components["schemas"]["RelatedAssetSignal"][];
            group_average: components["schemas"]["Decimal"];
            /** Format: date-time */
            calculated_at: string;
        };
        RelatedAssetSignal: {
            symbol: string;
            asset: string;
            exchange: string;
            change_percent: components["schemas"]["Decimal"];
            divergence_percent: components["schemas"]["Decimal"];
        };
        Alert: {
            id: string;
            dedup_key: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            /** @enum {string} */
            type: "triangular_arbitrage" | "cross_exchange_arbitrage" | "spot_futures_basis" | "ibkr_fx_triangular_arbitrage" | "crypto_spot_vs_ibkr_futures_basis" | "exchange_data_stale" | "exchange_disconnected" | "health_score_low";
            message: string;
            exchange?: string;
            symbol?: string;
            value: components["schemas"]["Decimal"];
            threshold: components["schemas"]["Decimal"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int32 */
            repeat_count: number;
            status: string;
        };
        Snapshot: {
            /** @example v2.1.0 */
            version: string;
            prices: {
                [key: string]: components["schemas"]["Ticker"][];
            };
            futures_prices: {
                [key: string]: components["schemas"]["Ticker"][];
            };
            order_books: components["schemas"]["OrderBook"][];
            order_book_summary: components["schemas"]["OrderBookSummary"][];
            funding_rates: components["schemas"]["FundingRate"][];
            markets: components["schemas"]["MarketInfo"][];
            triangular_arbitrage: components["schemas"]["TriangularOpportunityV2"][];
            cross_exchange_arbitrage: components["schemas"]["CrossExchangeOpportunityV2"][];
            spot_futures_arbitrage: components["schemas"]["SpotFuturesOpportunityV2"][];
            related_asset_signals: components["schemas"]["RelatedAssetGroupSignal"][];
            ibkr_instruments: components["schemas"]["MarketInfo"][];
            ibkr_fx_triangular: components["schemas"]["TriangularOpportunityV2"][];
            crypto_spot_vs_ibkr_futures_basis: components["schemas"]["BrokerFuturesBasisOpportunity"][];
            alerts: components["schemas"]["Alert"][];
            exchange_health: components["schemas"]["HealthMap"];
            provider_health: components["schemas"]["HealthMap"];
        };
    };
    responses: {
        /** @description Missing, invalid, or unconfigured API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getPrometheusMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Endpoint is not registered when Prometheus metrics are disabled. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest spot tickers, futures tickers, and funding rates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrderBooks: {
        parameters: {
            query?: {
                /**
                 * @description Lower-case provider identity such as `okx`, `bybit`, `binance`, `kraken`, `coinbase`, `gateio`, `bitget`, or `ibkr`.
                 * @example binance
                 */
                provider?: "okx" | "bybit" | "binance" | "kraken" | "coinbase" | "gateio" | "bitget" | "ibkr";
                /**
                 * @description Exchange display name such as `Binance` or `Kraken`.
                 * @example Binance
                 */
                exchange?: string;
                /**
                 * @description Canonical symbol.
                 * @example BTC/USDT
                 */
                symbol?: string;
                /**
                 * @description Market type.
                 * @example spot
                 */
                market?: components["schemas"]["MarketType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compact summaries by default, full order books when filtered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderBookSummary"][] | components["schemas"]["OrderBook"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured providers sorted by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProviderHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider health keyed by provider/exchange identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthMap"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTriangularArbitrage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Depth-aware triangular arbitrage estimates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriangularOpportunityV2"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCrossExchangeArbitrage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Depth-aware cross-exchange arbitrage estimates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossExchangeOpportunityV2"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSpotFuturesArbitrage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Depth-aware crypto spot-futures basis estimates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotFuturesOpportunityV2"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getIBKRInstruments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured IBKR instruments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketInfo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getIBKRFXTriangular: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description IBKR FX triangular estimates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriangularOpportunityV2"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getIBKRCryptoFuturesBasis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Crypto spot vs IBKR futures basis estimates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerFuturesBasisOpportunity"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRelatedAssetSignals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Related asset signal groups. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedAssetGroupSignal"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest in-memory alerts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getExchangeHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exchange health keyed by exchange/provider identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthMap"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate latest-state snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
